version: '3'

services:
  flask_ml:
    build:
      context: .
      dockerfile: dockerFileRepayment
    ports:
      - "5000:5000"
    image: fairtrade_flask_ml:1
  django:
    build:
      context: .
      dockerfile: dockerFileApp
    ports:
      - "8000:8000"
    image: fairtrade_django:1
    volumes:
      - sqlite_data:/data # Mount volume for SQLite data persistence
    depends_on:
      - flask_ml  

volumes:
  sqlite_data: