apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-ml
  template:
    metadata:
      labels:
        app: flask-ml
    spec:
      containers:
      - name: flask-ml
        image: ffairtrade_flask_ml:1
        ports:
        - containerPort: 5000
